version: '2'

services:
  redis:
    image: redis
    command: redis-server --requirepass 'xxxx' --appendonly yes
    volumes:
      - ./data/redis:/data

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: xxxxx
      POSTGRES_USER: xxxxx
      POSTGRES_PASSWORD: xxxxxx
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./log:/app/log
    depends_on: 
      - redis
      - postgresql
    entrypoint: ./entrypoint.sh
