version: '2'

services:
  app:
    build: .
    env_file:
      - app.local.env
    volumes:
      - .:/rails_demo
    command: bundle exec puma
    ports:
      - "3000:3000"
    links:
#      - redis
      - postgresql

#  redis:
#    image: redis:3.2
#    environment:
#      PASSWORD:
#    command: redis-server --requirepass $PASSWORD
#    volumes:
#      - ./data/redis:/data
#
  postgresql:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER:  test
      POSTGRES_PASSWORD:  test
      POSTGRES_DB: test
    volumes:
        - ./data/postgres:/var/lib/postgresql/data

