version: '2'

services:
  web:
    build: .
    command: bundle exec
    ports:
      - "3000:3000"
    links:
      - redis

  redis:
    build: redis/
#    environment:
#      PASSWORD:
#    command: redis-server --requirepass $PASSWORD
    volumes:
      - ./redis/data:/data



