apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: xxx
spec:
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30010
  selector:
    app: postgresql
  type: NodePort
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: postgresql
  namespace: xxx
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:10
        name: postgresql
        env:
          # Use secret in real usage
        - name: POSTGRES_PASSWORD
          value: 'xxxx'
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      # 持久化数据
      volumes:
      - name: postgresql-storage
        hostPath:
          path: /data/pgdata
      # 容器分配策略，根据node标签分配
      nodeSelector:
        kubernetes.io/hostname: xxxx
      # 容器重启策略
      restartPolicy: Always
